#!/usr/bin/env bash

usage() {
    cat >&2 <<-EOF
Usage ${0} [ OPTION... ] <INPUT FILE>
OPTIONS
  -a    Audio
  -A    Audio encoder
  -v    Video (default)
  -V    Video encoder
EOF
}

category=1
while getopts 'aAvV' opt; do
    case "${opt}" in
        a)
            category=2
            ;;
        A)
            category=4
            ;;
        v)
            category=1
            ;;
        V)
            category=3
            ;;
        ?)
            usage
            ;;
    esac
done

shift $((OPTIND-1))

if [[ $# -lt 1 ]]; then
    echo "ERROR: Missing arguments" >&2
    usage
    exit 1
fi

<"${1}" grep -E '^'${category} | awk 'BEGIN { FS=","; count=0; sum=0; } { sum+=$4; count++; } END { print sum / count; }'
