#!/usr/bin/env bash

usage() {
    cat >&2 <<-EOF
Usage ${0} [ OPTION... ] <INPUT FILE> <PERCENTILE>
OPTIONS
  -a    Audio
  -v    Video (default)
EOF
}

category=1
while getopts 'av' opt; do
    case "${opt}" in
        a)
            category=2
            ;;
        v)
            category=1
            ;;
        ?)
            usage
            ;;
    esac
done

shift $((OPTIND-1))

if [[ $# -lt 2 ]]; then
    echo "ERROR: Missing arguments" >&2
    usage
    exit 1
fi

set -x

<"${1}" grep -E '^'${category}'' \
    | sort -k4 -t, -g \
    | head -$(echo "scale=10; x=$(<"${1}" grep -E '^'${category} | wc -l)*(${2}/100); scale=0; x/1" | bc) \
    | tail -n-1
